### ISSUE TITLE
Article about webSockets

### ISSUE THREAD

**Issue by Lewiscowles1986** [closeio/making.close.com#75]
Hey there 👋

I just read your article about troubleshooting WebSocket connections.

https://making.close.com/posts/reliable-websockets/

You don't have any discussion or reach-out on the articles. I just wanted to ask a question if that's okay?

Rather than have frontend talk to the backend. Did you consider a TTL that is refreshed when the server pings, prior to or as a result of sending back pong? You'd mentioned redis in the article, so I'm guessing the concept of values which expire isn't new.

If you did, I'd love to know why you didn't select that approach? Maybe more blog fodder. 😉

Thank you for sharing. It was an interesting read!

**Comment by wojcikstefan** [comment]
Hi Lewis 👋 Thanks for taking the time to read our post and asking this (very good) question!

The mechanism you propose is solid and is used in e.g. socket.io. They specifically call it out in their [documentation](https://socket.io/docs/v4/how-it-works/#disconnection-detection):
> (...) if the client does not receive a PING packet within `pingInterval + pingTimeout`, it will consider that the connection is closed.

However, implementing this particular solution would require us to change the way we send pings from our servers and further divert from [RFC 6455](https://datatracker.ietf.org/doc/html/rfc6455) – something we weren't fully comfortable with.

Basically, because browsers don't expose any APIs to act on received Control Frames nor send Control Frames yourself (sadly, [W3C has rejected requests for this stuff years ago](https://www.w3.org/Bugs/Public/show_bug.cgi?id=13104)), **you can't implement a client-side TTL unless you send server-side pings as Data Frames.** We already had [SocketShark](https://github.com/closeio/socketshark) sending [`Ping` Control Frames](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2), so a) it seemed like more work to redo an already-working implementation of server-side pings, b) it feels a bit wrong to implement this mechanism yourself when the RFC specifies a dedicated way to do it.

Does that make sense?

**Comment by Lewiscowles1986** [comment]
I Love this answer. I Have been using Socket.IO, and thusly my mind was bent in that direction, shaped by the mold they made. Thank you again. It was a good read, and I hope you have a wonderful week. Thank you for answering me. 🙏
